export const medicineUnits = [
  {
    unitId: "UNIT-0001",
    drugTypeId: "DRUG-PCM-500",
    manufacturerId: "MFG-CIP-001",
    licenseId: "LIC-CIP-PCM-001",
    status: "Expired",
    createdAt: "4/15/2024",
    currentOwner: {
      id: "PHR-APL-003",
      type: "Pharmacy",
      name: "Apollo Pharmacy",
    },
    transferHistory: [
      {
        from: "Cipla Limited",
        to: "North India Pharmacy Network",
        timestamp: "4/16/2024, 10:30 AM",
        txnId: "TXN-PCM-0001",
      },
      {
        from: "North India Pharmacy Network",
        to: "Apollo Pharmacy",
        timestamp: "4/18/2024, 2:15 PM",
        txnId: "TXN-PCM-0002",
      },
    ],
    batch: "BATCH005",
  },
  {
    unitId: "UNIT-0002",
    drugTypeId: "DRUG-PCM-500",
    manufacturerId: "MFG-CIP-001",
    licenseId: "LIC-CIP-PCM-001",
    status: "Active",
    createdAt: "4/15/2024",
    currentOwner: {
      id: "MFG-CIP-001",
      type: "Manufacturer",
      name: "Cipla Limited",
    },
    transferHistory: [
      {
        from: "System",
        to: "Cipla Limited",
        timestamp: "4/15/2024, 9:00 AM",
        txnId: "TXN-PCM-0003",
      },
    ],
    batch: "BATCH005",
  },
  {
    unitId: "UNIT-0003",
    drugTypeId: "DRUG-ATV-020",
    manufacturerId: "MFG-CIP-001",
    licenseId: "LIC-CIP-ATV-004",
    status: "Expired",
    createdAt: "4/1/2024",
    currentOwner: {
      id: "PHR-MED-002",
      type: "Pharmacy",
      name: "MedPlus Pharmacy",
    },
    transferHistory: [
      {
        from: "Cipla Limited",
        to: "MediCare Pharmacy Network",
        timestamp: "4/2/2024, 11:45 AM",
        txnId: "TXN-ATV-0001",
      },
      {
        from: "MediCare Pharmacy Network",
        to: "MedPlus Pharmacy",
        timestamp: "4/4/2024, 4:20 PM",
        txnId: "TXN-ATV-0002",
      },
    ],
    batch: "BATCH004",
  },
  {
    unitId: "UNIT-0004",
    drugTypeId: "DRUG-ATV-020",
    manufacturerId: "MFG-CIP-001",
    licenseId: "LIC-CIP-ATV-004",
    status: "Sold",
    createdAt: "4/1/2024",
    currentOwner: {
      id: "BEN-66666666",
      type: "Citizen",
      name: "PM-JAY Beneficiary",
    },
    transferHistory: [
      {
        from: "Cipla Limited",
        to: "MedPlus Pharmacy",
        timestamp: "4/3/2024, 12:10 PM",
        txnId: "TXN-ATV-0003",
      },
      {
        from: "MedPlus Pharmacy",
        to: "Citizen",
        timestamp: "4/6/2024, 5:40 PM",
        txnId: "TXN-ATV-0004",
      },
    ],
    batch: "BATCH004",
  },
  {
    unitId: "UNIT-0005",
    drugTypeId: "DRUG-MET-500",
    manufacturerId: "MFG-SUN-002",
    licenseId: "LIC-SUN-MET-002",
    status: "Expired",
    createdAt: "3/10/2024",
    currentOwner: {
      id: "PHR-MED-002",
      type: "Pharmacy",
      name: "MedPlus Pharmacy",
    },
    transferHistory: [
      {
        from: "Sun Pharmaceuticals Ltd.",
        to: "MedPlus Pharmacy",
        timestamp: "3/12/2024, 1:30 PM",
        txnId: "TXN-MET-0001",
      },
    ],
    batch: "BATCH002",
  },
  {
    unitId: "UNIT-0006",
    drugTypeId: "DRUG-MET-500",
    manufacturerId: "MFG-SUN-002",
    licenseId: "LIC-SUN-MET-002",
    status: "Active",
    createdAt: "3/10/2024",
    currentOwner: {
      id: "MFG-SUN-002",
      type: "Manufacturer",
      name: "Sun Pharmaceuticals Ltd.",
    },
    transferHistory: [
      {
        from: "System",
        to: "Sun Pharmaceuticals Ltd.",
        timestamp: "3/10/2024, 9:15 AM",
        txnId: "TXN-MET-0002",
      },
    ],
    batch: "BATCH002",
  },
  {
    unitId: "UNIT-0007",
    drugTypeId: "DRUG-AMX-500",
    manufacturerId: "MFG-SUN-002",
    licenseId: "LIC-SUN-AMX-001",
    status: "Sold",
    createdAt: "2/20/2024",
    currentOwner: {
      id: "BEN-66666666",
      type: "Citizen",
      name: "PM-JAY Beneficiary",
    },
    transferHistory: [
      {
        from: "Sun Pharmaceuticals Ltd.",
        to: "Apollo Pharmacy",
        timestamp: "2/22/2024, 3:00 PM",
        txnId: "TXN-AMX-0001",
      },
      {
        from: "Apollo Pharmacy",
        to: "Citizen",
        timestamp: "2/25/2024, 6:25 PM",
        txnId: "TXN-AMX-0002",
      },
    ],
    batch: "BATCH001",
  },
  {
    unitId: "UNIT-0008",
    drugTypeId: "DRUG-AMX-500",
    manufacturerId: "MFG-SUN-002",
    licenseId: "LIC-SUN-AMX-001",
    status: "Recalled",
    createdAt: "2/20/2024",
    currentOwner: {
      id: "PHR-APL-003",
      type: "Pharmacy",
      name: "Apollo Pharmacy",
    },
    transferHistory: [
      {
        from: "Sun Pharmaceuticals Ltd.",
        to: "Apollo Pharmacy",
        timestamp: "2/22/2024, 3:00 PM",
        txnId: "TXN-AMX-0003",
      },
      {
        from: "CDSCO",
        to: "Apollo Pharmacy",
        timestamp: "3/1/2024, 10:00 AM",
        txnId: "TXN-RECALL-0001",
      },
    ],
    batch: "BATCH001",
  },
];